<a href="https://colab.research.google.com/github/datascience-vivek/cv_test/blob/main/CV_Test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
df = pd.read_csv('/content/drive/MyDrive/ML Class/Advertising.csv', index_col=[0])
df

TV  Radio  Newspaper  Sales
1    230.1   37.8       69.2   22.1
2     44.5   39.3       45.1   10.4
3     17.2   45.9       69.3    9.3
4    151.5   41.3       58.5   18.5
5    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
196   38.2    3.7       13.8    7.6
197   94.2    4.9        8.1    9.7
198  177.0    9.3        6.4   12.8
199  283.6   42.0       66.2   25.5
200  232.1    8.6        8.7   13.4

[200 rows x 4 columns]

In [4]:
x = df.drop(['Sales'], axis= 1)
x

TV  Radio  Newspaper
1    230.1   37.8       69.2
2     44.5   39.3       45.1
3     17.2   45.9       69.3
4    151.5   41.3       58.5
5    180.8   10.8       58.4
..     ...    ...        ...
196   38.2    3.7       13.8
197   94.2    4.9        8.1
198  177.0    9.3        6.4
199  283.6   42.0       66.2
200  232.1    8.6        8.7

[200 rows x 3 columns]

In [5]:
y = df['Sales']
y

1      22.1
2      10.4
3       9.3
4      18.5
5      12.9
       ... 
196     7.6
197     9.7
198    12.8
199    25.5
200    13.4
Name: Sales, Length: 200, dtype: float64

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
x_train, x_test, y_train, y_test, = train_test_split(x,y, test_size=0.3, random_state= 101)

In [8]:
from sklearn.preprocessing import StandardScaler

In [9]:
scaler = StandardScaler()

In [10]:
scaler.fit(x_train)

StandardScaler()

In [11]:
scaler.fit(x_train)
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

In [12]:
x_test = scaler.transform(x_test)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


In [13]:
from sklearn.linear_model import Ridge

In [14]:
model = Ridge(alpha=100)

In [15]:
model.fit(x_train, y_train)

Ridge(alpha=100)

In [16]:
y_pred = model.predict(x_test)

In [17]:
from sklearn.metrics import mean_squared_error

In [18]:
MSE= mean_squared_error(y_pred, y_test)
MSE

64.21922374548488

In [19]:
model2 = Ridge(alpha=1)

In [20]:
model2.fit(x_train, y_train)

Ridge(alpha=1)

In [21]:
ypred2 = model2.predict(x_test)

In [22]:
MSE = mean_squared_error(ypred2, y_test)
MSE

129.6990400216778

In [23]:
x_train, x_other, y_train, y_other, = train_test_split(x,y, test_size=0.3, random_state= 101)

In [24]:
#Test size = 0.5(50% of the 30% other data)
x_eval, x_test, y_eval, y_test = train_test_split(x_other, y_other, test_size= 0.5, random_state=101)

In [25]:
len(df)

200

In [26]:
len(x_train)

140

In [27]:
len(x_other)

60

In [28]:
len(x_eval)

30

In [29]:
len(x_test)

30

In [30]:
x_train = scaler.transform(x_train)

In [31]:
x_test = scaler.transform(x_test)

In [32]:
x_eval = scaler.transform(x_eval)#validation data

In [33]:
model3= Ridge(alpha=100)

In [34]:
model3.fit(x_train, y_train)

Ridge(alpha=100)

In [35]:
y_eval_pred = model3.predict(x_eval)
y_eval_pred

array([16.0980788 , 10.8495293 ,  8.75095421, 14.83525505, 12.55896716,
       12.8883864 , 11.58372535, 12.01609545, 16.18778637, 10.90016204,
       11.32616781, 17.90771073, 14.09264772, 13.79206361, 13.71636726,
        9.87999576, 15.34908128, 13.00876939, 13.43419788, 10.85075815,
       14.75707677, 18.83377117, 17.30158479, 15.74187916, 16.49277745,
       19.66643199, 17.6105132 , 10.07145317, 13.64670913, 17.42108555])

In [36]:
MSE = mean_squared_error(y_eval_pred, y_eval)
MSE

7.320101458823871

In [37]:
model4= Ridge(alpha=1)

In [38]:
model4.fit(x_train, y_train)

Ridge(alpha=1)

In [39]:
new_pred_eval = model4.predict(x_eval)

In [40]:
MSE = mean_squared_error(new_pred_eval, y_eval)
MSE

2.383783075056986

In [41]:
RMSE= np.sqrt(MSE)
RMSE

1.5439504768796783

In [42]:
y_final_test_pred = model4.predict(x_test)##Final evaluation on the test 

In [43]:
MSE = mean_squared_error(y_test,y_final_test_pred )##For training testing and validation case
MSE

2.2542600838005176

In [44]:
RMSE= np.sqrt(MSE)
RMSE

1.5014193564093004

In [45]:
#Cross_VAL_Score(K-fold CV)

In [46]:
from sklearn.model_selection import cross_val_score

In [47]:
model = Ridge(alpha=100)

In [48]:
scores = cross_val_score(model, x_train, y_train,scoring = 'neg_mean_squared_error', cv=5)

In [49]:
scores

array([ -9.32552967,  -4.9449624 , -11.39665242,  -7.0242106 ,
        -8.38562723])

In [50]:
abs(scores.mean())

8.215396464543607

In [51]:
model2 = Ridge(alpha=1)

In [52]:
scores3 = cross_val_score(model2, x_train, y_train,scoring = 'neg_mean_squared_error', cv=5)

In [53]:
scores3

array([-3.15513238, -1.58086982, -5.40455562, -2.21654481, -4.36709384])

In [54]:
abs(scores3.mean())

3.344839296530695

In [55]:
model2.fit(x_train, y_train)

Ridge(alpha=1)

In [56]:
y_final_test_pred = model2.predict(x_test)## Prediction on the final test(final evluation)

In [57]:
MSE = mean_squared_error(y_test,y_final_test_pred )##For training testing and validation case
MSE

2.2542600838005176

In [58]:
##Cross validate function
from sklearn.model_selection import cross_validate

In [59]:
model = Ridge(alpha=100)

In [60]:
scores = cross_validate(model, x_train, y_train, scoring= ['neg_mean_squared_error', 'neg_mean_absolute_error'], cv=5)

In [61]:
scores = pd.DataFrame(scores)
scores

fit_time  score_time  test_neg_mean_squared_error  \
0  0.007072    0.001382                    -9.325530   
1  0.013189    0.001194                    -4.944962   
2  0.001800    0.001027                   -11.396652   
3  0.009161    0.003262                    -7.024211   
4  0.003661    0.001081                    -8.385627   

   test_neg_mean_absolute_error  
0                     -2.312430  
1                     -1.746534  
2                     -2.562117  
3                     -2.018732  
4                     -2.279519

In [62]:
scores.mean()

fit_time                        0.006977
score_time                      0.001589
test_neg_mean_squared_error    -8.215396
test_neg_mean_absolute_error   -2.183866
dtype: float64

In [63]:
model1 = Ridge(alpha=1)

In [64]:
scores1 = cross_validate(model1, x_train, y_train, scoring= ['neg_mean_squared_error', 'neg_mean_absolute_error'], cv=5)

In [65]:
scores1 = pd.DataFrame(scores)
scores1

fit_time  score_time  test_neg_mean_squared_error  \
0  0.007072    0.001382                    -9.325530   
1  0.013189    0.001194                    -4.944962   
2  0.001800    0.001027                   -11.396652   
3  0.009161    0.003262                    -7.024211   
4  0.003661    0.001081                    -8.385627   

   test_neg_mean_absolute_error  
0                     -2.312430  
1                     -1.746534  
2                     -2.562117  
3                     -2.018732  
4                     -2.279519

In [66]:
scores1.mean()

fit_time                        0.006977
score_time                      0.001589
test_neg_mean_squared_error    -8.215396
test_neg_mean_absolute_error   -2.183866
dtype: float64

In [67]:
model1.fit(x_train, y_train)

Ridge(alpha=1)

In [68]:
y_final_pred1 = model1.predict(x_test)

In [69]:
mean_squared_error(y_test, y_final_pred1)

2.2542600838005176

In [70]:
##Elastic Net
from sklearn.linear_model import ElasticNet

In [72]:
base_elastic_model = ElasticNet()

In [73]:
param_grid = {'alpha': [0.1,1,5,10,100], 'l1_ratio':[0.1,0.5,0.7,0.9,1]}

In [76]:
from sklearn.model_selection import GridSearchCV

In [79]:
grid_model = GridSearchCV(estimator = base_elastic_model, param_grid= param_grid, scoring='neg_mean_squared_error', cv= 5, verbose = 2)

In [80]:
grid_model.fit(x_train, y_train)

Fitting 5 folds for each of 25 candidates, totalling 125 fits
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.7; total time=   0.0s
[CV] END ............................alpha=0.1,

GridSearchCV(cv=5, estimator=ElasticNet(),
             param_grid={'alpha': [0.1, 1, 5, 10, 100],
                         'l1_ratio': [0.1, 0.5, 0.7, 0.9, 1]},
             scoring='neg_mean_squared_error', verbose=2)

In [82]:
grid_model.best_estimator_

ElasticNet(alpha=0.1, l1_ratio=1)

In [83]:
grid_model.best_params_

{'alpha': 0.1, 'l1_ratio': 1}

In [84]:
pd.DataFrame(grid_model.cv_results_).head()

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_alpha  \
0       0.001405      0.000428         0.000698        0.000361         0.1   
1       0.000833      0.000040         0.000340        0.000016         0.1   
2       0.001187      0.000281         0.000380        0.000044         0.1   
3       0.001425      0.000342         0.000398        0.000046         0.1   
4       0.001231      0.000268         0.000413        0.000073         0.1   

  param_l1_ratio                           params  split0_test_score  \
0            0.1  {'alpha': 0.1, 'l1_ratio': 0.1}          -3.453021   
1            0.5  {'alpha': 0.1, 'l1_ratio': 0.5}          -3.325440   
2            0.7  {'alpha': 0.1, 'l1_ratio': 0.7}          -3.269880   
3            0.9  {'alpha': 0.1, 'l1_ratio': 0.9}          -3.221397   
4              1    {'alpha': 0.1, 'l1_ratio': 1}          -3.206943   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0          -1.405190          -5.789125          -2.187302          -4.645576   
1          -1.427522          -5.595610          -2.163089          -4.451679   
2          -1.442432          -5.502437          -2.163950          -4.356738   
3          -1.465339          -5.416447          -2.173493          -4.263887   
4          -1.480065          -5.376257          -2.182076          -4.218460   

   mean_test_score  std_test_score  rank_test_score  
0        -3.496043        1.591601                5  
1        -3.392668        1.506827                4  
2        -3.347088        1.462765                3  
3        -3.308112        1.417693                2  
4        -3.292760        1.394613                1

In [86]:
y_pred = grid_model.predict(x_test)

In [87]:
mean_squared_error(y_test, y_pred)

2.304617137424956